from django.urls import path

from .mobile_api import (
    employee_checklist_complete_api_view,
    employee_checklist_detail_api_view,
    employee_checklists_api_view,
    employee_course_complete_api_view,
    employee_course_detail_api_view,
    employee_courses_api_view,
    employee_dashboard_api_view,
    employee_exam_start_api_view,
    employee_exam_submit_api_view,
    employee_learning_history_api_view,
    mobile_forgot_password_view,
    mobile_login_view,
    mobile_register_view,
    mobile_notifications_api_view,
    mobile_logout_view,
    mobile_me_view,
    owner_assign_course_api_view,
    owner_checklist_create_api_view,
    owner_checklist_rule_create_api_view,
    owner_checklist_rules_api_view,
    owner_checklists_api_view,
    owner_course_content_create_api_view,
    owner_course_content_delete_api_view,
    owner_course_content_update_api_view,
    owner_course_detail_api_view,
    owner_course_create_api_view,
    owner_courses_api_view,
    owner_dashboard_api_view,
    owner_employee_deactivate_api_view,
    owner_employee_create_api_view,
    owner_employees_api_view,
    owner_job_title_create_api_view,
    owner_job_titles_api_view,
    owner_reports_api_view,
    mobile_private_chat_api_view,
    mobile_private_chat_send_api_view,
    mobile_team_chat_api_view,
    mobile_team_chat_send_api_view,
)


urlpatterns = [
    path('auth/register/', mobile_register_view, name='mobile_register'),
    path('auth/login/', mobile_login_view, name='mobile_login'),
    path('auth/logout/', mobile_logout_view, name='mobile_logout'),
    path('auth/me/', mobile_me_view, name='mobile_me'),
    path('auth/forgot-password/', mobile_forgot_password_view, name='mobile_forgot_password'),
    path('notifications/', mobile_notifications_api_view, name='mobile_notifications'),
    path('employee/dashboard/', employee_dashboard_api_view, name='mobile_employee_dashboard'),
    path('employee/courses/', employee_courses_api_view, name='mobile_employee_courses'),
    path('employee/learning-history/', employee_learning_history_api_view, name='mobile_employee_learning_history'),
    path('employee/courses/<int:assignment_id>/', employee_course_detail_api_view, name='mobile_employee_course_detail'),
    path('employee/courses/<int:assignment_id>/complete/', employee_course_complete_api_view, name='mobile_employee_course_complete'),
    path('employee/courses/<int:assignment_id>/exam/start/', employee_exam_start_api_view, name='mobile_employee_exam_start'),
    path('employee/courses/<int:assignment_id>/exam/submit/', employee_exam_submit_api_view, name='mobile_employee_exam_submit'),
    path('employee/checklists/', employee_checklists_api_view, name='mobile_employee_checklists'),
    path('employee/checklists/<int:checklist_id>/', employee_checklist_detail_api_view, name='mobile_employee_checklist_detail'),
    path('employee/checklists/<int:checklist_id>/complete/', employee_checklist_complete_api_view, name='mobile_employee_checklist_complete'),
    path('employee/chat/team/', mobile_team_chat_api_view, {'role': 'employee'}, name='mobile_employee_team_chat'),
    path('employee/chat/team/send/', mobile_team_chat_send_api_view, {'role': 'employee'}, name='mobile_employee_team_chat_send'),
    path('employee/chat/private/', mobile_private_chat_api_view, {'role': 'employee'}, name='mobile_employee_private_chat'),
    path('employee/chat/private/send/', mobile_private_chat_send_api_view, {'role': 'employee'}, name='mobile_employee_private_chat_send'),
    path('business-owner/dashboard/', owner_dashboard_api_view, name='mobile_owner_dashboard'),
    path('business-owner/employees/', owner_employees_api_view, name='mobile_owner_employees'),
    path('business-owner/employees/<int:employee_id>/deactivate/', owner_employee_deactivate_api_view, name='mobile_owner_employee_deactivate'),
    path('business-owner/employees/create/', owner_employee_create_api_view, name='mobile_owner_employee_create'),
    path('business-owner/job-titles/', owner_job_titles_api_view, name='mobile_owner_job_titles'),
    path('business-owner/job-titles/create/', owner_job_title_create_api_view, name='mobile_owner_job_title_create'),
    path('business-owner/courses/', owner_courses_api_view, name='mobile_owner_courses'),
    path('business-owner/courses/create/', owner_course_create_api_view, name='mobile_owner_course_create'),
    path('business-owner/courses/<int:course_id>/', owner_course_detail_api_view, name='mobile_owner_course_detail'),
    path('business-owner/courses/<int:course_id>/content/create/', owner_course_content_create_api_view, name='mobile_owner_course_content_create'),
    path('business-owner/course-content/<int:item_id>/update/', owner_course_content_update_api_view, name='mobile_owner_course_content_update'),
    path('business-owner/course-content/<int:item_id>/delete/', owner_course_content_delete_api_view, name='mobile_owner_course_content_delete'),
    path('business-owner/courses/<int:course_id>/assign/', owner_assign_course_api_view, name='mobile_owner_course_assign'),
    path('business-owner/reports/', owner_reports_api_view, name='mobile_owner_reports'),
    path('business-owner/checklists/', owner_checklists_api_view, name='mobile_owner_checklists'),
    path('business-owner/checklists/create/', owner_checklist_create_api_view, name='mobile_owner_checklist_create'),
    path('business-owner/checklist-rules/', owner_checklist_rules_api_view, name='mobile_owner_checklist_rules'),
    path('business-owner/checklist-rules/create/', owner_checklist_rule_create_api_view, name='mobile_owner_checklist_rule_create'),
    path('business-owner/chat/team/', mobile_team_chat_api_view, {'role': 'business_owner'}, name='mobile_owner_team_chat'),
    path('business-owner/chat/team/send/', mobile_team_chat_send_api_view, {'role': 'business_owner'}, name='mobile_owner_team_chat_send'),
    path('business-owner/chat/private/', mobile_private_chat_api_view, {'role': 'business_owner'}, name='mobile_owner_private_chat'),
    path('business-owner/chat/private/send/', mobile_private_chat_send_api_view, {'role': 'business_owner'}, name='mobile_owner_private_chat_send'),
]
