from django.urls import path

from .mobile_api import (
    employee_checklist_complete_api_view,
    employee_checklist_detail_api_view,
    employee_checklists_api_view,
    employee_course_complete_api_view,
    employee_course_detail_api_view,
    employee_courses_api_view,
    employee_dashboard_api_view,
    employee_exam_start_api_view,
    employee_exam_submit_api_view,
    mobile_login_view,
    mobile_logout_view,
    mobile_me_view,
    owner_assign_course_api_view,
    owner_checklist_create_api_view,
    owner_checklists_api_view,
    owner_course_detail_api_view,
    owner_course_create_api_view,
    owner_courses_api_view,
    owner_dashboard_api_view,
    owner_employee_create_api_view,
    owner_employees_api_view,
    owner_reports_api_view,
)


urlpatterns = [
    path('auth/login/', mobile_login_view, name='mobile_login'),
    path('auth/logout/', mobile_logout_view, name='mobile_logout'),
    path('auth/me/', mobile_me_view, name='mobile_me'),
    path('employee/dashboard/', employee_dashboard_api_view, name='mobile_employee_dashboard'),
    path('employee/courses/', employee_courses_api_view, name='mobile_employee_courses'),
    path('employee/courses/<int:assignment_id>/', employee_course_detail_api_view, name='mobile_employee_course_detail'),
    path('employee/courses/<int:assignment_id>/complete/', employee_course_complete_api_view, name='mobile_employee_course_complete'),
    path('employee/courses/<int:assignment_id>/exam/start/', employee_exam_start_api_view, name='mobile_employee_exam_start'),
    path('employee/courses/<int:assignment_id>/exam/submit/', employee_exam_submit_api_view, name='mobile_employee_exam_submit'),
    path('employee/checklists/', employee_checklists_api_view, name='mobile_employee_checklists'),
    path('employee/checklists/<int:checklist_id>/', employee_checklist_detail_api_view, name='mobile_employee_checklist_detail'),
    path('employee/checklists/<int:checklist_id>/complete/', employee_checklist_complete_api_view, name='mobile_employee_checklist_complete'),
    path('business-owner/dashboard/', owner_dashboard_api_view, name='mobile_owner_dashboard'),
    path('business-owner/employees/', owner_employees_api_view, name='mobile_owner_employees'),
    path('business-owner/employees/create/', owner_employee_create_api_view, name='mobile_owner_employee_create'),
    path('business-owner/courses/', owner_courses_api_view, name='mobile_owner_courses'),
    path('business-owner/courses/create/', owner_course_create_api_view, name='mobile_owner_course_create'),
    path('business-owner/courses/<int:course_id>/', owner_course_detail_api_view, name='mobile_owner_course_detail'),
    path('business-owner/courses/<int:course_id>/assign/', owner_assign_course_api_view, name='mobile_owner_course_assign'),
    path('business-owner/reports/', owner_reports_api_view, name='mobile_owner_reports'),
    path('business-owner/checklists/', owner_checklists_api_view, name='mobile_owner_checklists'),
    path('business-owner/checklists/create/', owner_checklist_create_api_view, name='mobile_owner_checklist_create'),
]
