from django.urls import path

from .views import (
    business_owner_checklist_assignment_rule_create_action,
    business_owner_checklist_create_action,
    business_owner_checklists_view,
    business_owner_course_assignment_rule_create_action,
    business_owner_course_content_create_action,
    business_owner_course_content_delete_action,
    business_owner_course_content_update_action,
    business_owner_course_content_view,
    business_owner_courses_view,
    business_owner_dashboard_view,
    business_owner_employee_create_action,
    business_owner_employees_view,
    business_owner_job_title_create_action,
    business_owner_scorm_library_view,
    business_owner_course_create_action,
    employee_checklist_complete_action,
    employee_checklists_view,
    employee_course_complete_action,
    employee_course_view,
    employee_courses_view,
    employee_dashboard_view,
    employee_scorm_check_complete_action,
    employee_scorm_course_view,
    employee_scorm_courses_view,
    home_view,
    login_view,
    logout_view,
    register_view,
    scorm_player_file_redirect_view,
    scorm_player_file_view,
)


urlpatterns = [
    path('', home_view, name='home'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('business-owner/dashboard/', business_owner_dashboard_view, name='business_owner_dashboard'),
    path('business-owner/employees/', business_owner_employees_view, name='business_owner_employees'),
    path('business-owner/courses/', business_owner_courses_view, name='business_owner_courses'),
    path('business-owner/course-content/', business_owner_course_content_view, name='business_owner_course_content'),
    path('business-owner/checklists/', business_owner_checklists_view, name='business_owner_checklists'),
    path('business-owner/scorm/', business_owner_scorm_library_view, name='business_owner_scorm'),
    path('business-owner/job-titles/create/', business_owner_job_title_create_action, name='business_owner_job_title_create'),
    path('business-owner/employees/create/', business_owner_employee_create_action, name='business_owner_employee_create'),
    path('business-owner/courses/create/', business_owner_course_create_action, name='business_owner_course_create'),
    path('business-owner/course-content/create/', business_owner_course_content_create_action, name='business_owner_course_content_create'),
    path('business-owner/course-content/<int:item_id>/update/', business_owner_course_content_update_action, name='business_owner_course_content_update'),
    path('business-owner/course-content/<int:item_id>/delete/', business_owner_course_content_delete_action, name='business_owner_course_content_delete'),
    path('business-owner/course-rules/create/', business_owner_course_assignment_rule_create_action, name='business_owner_course_rule_create'),
    path('business-owner/checklists/create/', business_owner_checklist_create_action, name='business_owner_checklist_create'),
    path('business-owner/checklist-rules/create/', business_owner_checklist_assignment_rule_create_action, name='business_owner_checklist_rule_create'),
    path('employee/dashboard/', employee_dashboard_view, name='employee_dashboard'),
    path('employee/courses/', employee_courses_view, name='employee_courses'),
    path('employee/courses/<int:assignment_id>/', employee_course_view, name='employee_course_view'),
    path('employee/checklists/', employee_checklists_view, name='employee_checklists'),
    path('employee/scorm/', employee_scorm_courses_view, name='employee_scorm_courses'),
    path('employee/scorm/<str:filename>/', employee_scorm_course_view, name='employee_scorm_course_view'),
    path('employee/scorm/<str:filename>/check-complete/', employee_scorm_check_complete_action, name='employee_scorm_check_complete_action'),
    path('employee/courses/<int:assignment_id>/complete/', employee_course_complete_action, name='employee_course_complete'),
    path('employee/checklists/<int:checklist_id>/complete/', employee_checklist_complete_action, name='employee_checklist_complete'),
    path('scorm/player/<str:folder>/<path:filepath>', scorm_player_file_view, name='scorm_player_file'),
    path('scorm/player/<str:folder>/<path:filepath>/', scorm_player_file_redirect_view, name='scorm_player_file_slash_redirect'),
]
