from django.urls import path

from .views import (
    business_owner_checklist_assignment_rule_create_action,
    business_owner_checklist_create_action,
    business_owner_checklists_view,
    business_owner_course_assignment_rule_create_action,
    business_owner_course_content_create_action,
    business_owner_course_content_delete_action,
    business_owner_course_content_update_action,
    business_owner_course_content_view,
    business_owner_courses_view,
    business_owner_dashboard_view,
    business_owner_employee_create_action,
    business_owner_employees_view,
    business_owner_job_title_create_action,
    business_owner_scorm_library_view,
    business_owner_course_create_action,
    employee_checklist_complete_action,
    employee_checklists_view,
    employee_course_complete_action,
    employee_course_exam_view,
    employee_course_exam_submit_action,
    employee_course_exam_take_view,
    employee_course_view,
    employee_courses_view,
    employee_dashboard_view,
    employee_learning_history_view,
    employee_scorm_check_complete_action,
    employee_scorm_course_view,
    employee_scorm_courses_view,
    home_view,
    login_view,
    logout_view,
    register_view,
    scorm_player_file_redirect_view,
    scorm_player_file_view,
    super_admin_business_create_action,
    super_admin_business_toggle_action,
    super_admin_businesses_view,
    super_admin_checklist_toggle_action,
    super_admin_course_assignment_rule_create_action,
    super_admin_course_content_create_action,
    super_admin_course_create_action,
    super_admin_course_toggle_action,
    super_admin_dashboard_view,
    super_admin_exam_grading_view,
    super_admin_exam_question_delete_action,
    super_admin_exam_question_editor_view,
    super_admin_exam_sessions_view,
    super_admin_exam_template_editor_view,
    super_admin_exam_templates_view,
    super_admin_learning_view,
    super_admin_operations_view,
    super_admin_publish_employee_catalog_action,
    super_admin_scorm_library_view,
    super_admin_user_create_action,
    super_admin_user_toggle_active_action,
    super_admin_user_toggle_role_action,
    super_admin_users_view,
)


urlpatterns = [
    path('', home_view, name='home'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('super-admin/dashboard/', super_admin_dashboard_view, name='super_admin_dashboard'),
    path('super-admin/businesses/', super_admin_businesses_view, name='super_admin_businesses'),
    path('super-admin/businesses/create/', super_admin_business_create_action, name='super_admin_business_create'),
    path('super-admin/businesses/<int:business_id>/toggle/', super_admin_business_toggle_action, name='super_admin_business_toggle'),
    path('super-admin/users/', super_admin_users_view, name='super_admin_users'),
    path('super-admin/users/create/', super_admin_user_create_action, name='super_admin_user_create'),
    path('super-admin/users/<int:user_id>/toggle-active/', super_admin_user_toggle_active_action, name='super_admin_user_toggle_active'),
    path('super-admin/users/<int:user_id>/toggle-role/', super_admin_user_toggle_role_action, name='super_admin_user_toggle_role'),
    path('super-admin/learning/', super_admin_learning_view, name='super_admin_learning'),
    path('super-admin/learning/exams/templates/', super_admin_exam_templates_view, name='super_admin_exam_templates'),
    path('super-admin/learning/exams/templates/create/', super_admin_exam_template_editor_view, name='super_admin_exam_template_create'),
    path('super-admin/learning/exams/templates/<int:template_id>/', super_admin_exam_template_editor_view, name='super_admin_exam_template_editor'),
    path('super-admin/learning/exams/templates/<int:template_id>/questions/create/', super_admin_exam_question_editor_view, name='super_admin_exam_question_create'),
    path('super-admin/learning/exams/templates/<int:template_id>/questions/<int:question_id>/', super_admin_exam_question_editor_view, name='super_admin_exam_question_editor'),
    path('super-admin/learning/exams/templates/<int:template_id>/questions/<int:question_id>/delete/', super_admin_exam_question_delete_action, name='super_admin_exam_question_delete'),
    path('super-admin/learning/exams/sessions/', super_admin_exam_sessions_view, name='super_admin_exam_sessions'),
    path('super-admin/learning/exams/grading/', super_admin_exam_grading_view, name='super_admin_exam_grading'),
    path('super-admin/learning/courses/create/', super_admin_course_create_action, name='super_admin_course_create'),
    path('super-admin/learning/course-rules/create/', super_admin_course_assignment_rule_create_action, name='super_admin_course_rule_create'),
    path('super-admin/learning/course-content/create/', super_admin_course_content_create_action, name='super_admin_course_content_create'),
    path('super-admin/learning/catalog/publish/', super_admin_publish_employee_catalog_action, name='super_admin_publish_employee_catalog'),
    path('super-admin/learning/courses/<int:course_id>/toggle/', super_admin_course_toggle_action, name='super_admin_course_toggle'),
    path('super-admin/learning/checklists/<int:checklist_id>/toggle/', super_admin_checklist_toggle_action, name='super_admin_checklist_toggle'),
    path('super-admin/operations/', super_admin_operations_view, name='super_admin_operations'),
    path('super-admin/scorm/', super_admin_scorm_library_view, name='super_admin_scorm'),
    path('business-owner/dashboard/', business_owner_dashboard_view, name='business_owner_dashboard'),
    path('business-owner/employees/', business_owner_employees_view, name='business_owner_employees'),
    path('business-owner/courses/', business_owner_courses_view, name='business_owner_courses'),
    path('business-owner/course-content/', business_owner_course_content_view, name='business_owner_course_content'),
    path('business-owner/checklists/', business_owner_checklists_view, name='business_owner_checklists'),
    path('business-owner/scorm/', business_owner_scorm_library_view, name='business_owner_scorm'),
    path('business-owner/job-titles/create/', business_owner_job_title_create_action, name='business_owner_job_title_create'),
    path('business-owner/employees/create/', business_owner_employee_create_action, name='business_owner_employee_create'),
    path('business-owner/courses/create/', business_owner_course_create_action, name='business_owner_course_create'),
    path('business-owner/course-content/create/', business_owner_course_content_create_action, name='business_owner_course_content_create'),
    path('business-owner/course-content/<int:item_id>/update/', business_owner_course_content_update_action, name='business_owner_course_content_update'),
    path('business-owner/course-content/<int:item_id>/delete/', business_owner_course_content_delete_action, name='business_owner_course_content_delete'),
    path('business-owner/course-rules/create/', business_owner_course_assignment_rule_create_action, name='business_owner_course_rule_create'),
    path('business-owner/checklists/create/', business_owner_checklist_create_action, name='business_owner_checklist_create'),
    path('business-owner/checklist-rules/create/', business_owner_checklist_assignment_rule_create_action, name='business_owner_checklist_rule_create'),
    path('employee/dashboard/', employee_dashboard_view, name='employee_dashboard'),
    path('employee/courses/', employee_courses_view, name='employee_courses'),
    path('employee/learning-history/', employee_learning_history_view, name='employee_learning_history'),
    path('employee/courses/<int:assignment_id>/', employee_course_view, name='employee_course_view'),
    path('employee/courses/<int:assignment_id>/exam/', employee_course_exam_view, name='employee_course_exam'),
    path('employee/courses/<int:assignment_id>/exam/take/', employee_course_exam_take_view, name='employee_course_exam_take'),
    path('employee/courses/<int:assignment_id>/exam/submit/', employee_course_exam_submit_action, name='employee_course_exam_submit'),
    path('employee/checklists/', employee_checklists_view, name='employee_checklists'),
    path('employee/scorm/', employee_scorm_courses_view, name='employee_scorm_courses'),
    path('employee/scorm/<str:filename>/', employee_scorm_course_view, name='employee_scorm_course_view'),
    path('employee/scorm/<str:filename>/check-complete/', employee_scorm_check_complete_action, name='employee_scorm_check_complete_action'),
    path('employee/courses/<int:assignment_id>/complete/', employee_course_complete_action, name='employee_course_complete'),
    path('employee/checklists/<int:checklist_id>/complete/', employee_checklist_complete_action, name='employee_checklist_complete'),
    path('scorm/player/<str:folder>/<path:filepath>', scorm_player_file_view, name='scorm_player_file'),
    path('scorm/player/<str:folder>/<path:filepath>/', scorm_player_file_redirect_view, name='scorm_player_file_slash_redirect'),
]
