# Generated by Django 6.0.2 on 2026-02-27 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_initial'),
        ('progress', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.role'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitemresult',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklist_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='learning.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='checklistitemresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='progress.checklistrun'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.quizattempt'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'is_active'], name='progress_as_tenant__ba216e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_at'], name='progress_as_due_at_720072_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['tenant', 'issued_at'], name='progress_ce_tenant__99bcf6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['code'], name='progress_ce_code_9ff8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrun',
            index=models.Index(fields=['tenant', 'performed_at'], name='progress_ch_tenant__c8cb76_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrun',
            index=models.Index(fields=['branch', 'performed_at'], name='progress_ch_branch__d9b49a_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitemresult',
            index=models.Index(fields=['run'], name='progress_ch_run_id_1a70e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistitemresult',
            constraint=models.UniqueConstraint(fields=('run', 'item'), name='uq_run_item'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'completed_at'], name='progress_en_tenant__7a06f0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'completed_at'], name='progress_en_user_id_835352_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uq_enroll_user_course'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'path'), name='uq_enroll_user_path'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['tenant', 'completed_at'], name='progress_le_tenant__42ba2e_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'completed_at'], name='progress_le_user_id_80ca46_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uq_user_lesson_progress'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['tenant', 'submitted_at'], name='progress_qu_tenant__829487_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'submitted_at'], name='progress_qu_user_id_18a7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['attempt', 'question_id'], name='progress_qu_attempt_58a63a_idx'),
        ),
    ]
