import 'package:flutter/material.dart';

enum AppLanguage { en, ar }

class AppLanguageController {
  static ValueChanged<AppLanguage>? onChange;
}

bool isArabic(BuildContext context) =>
    Localizations.localeOf(context).languageCode == 'ar';

String tr(BuildContext context, String english) {
  if (!isArabic(context)) {
    return english;
  }
  return arabicStrings[english] ?? english;
}

const Map<String, String> arabicStrings = {
  'Reset Password': 'Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙŠÙŠÙ† ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
  'Reset your password using your username and the recovery email saved on your account.':
      'Ø£Ø¹Ø¯ ØªØ¹ÙŠÙŠÙ† ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… ÙˆØ§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ø§Ù„Ù…Ø³Ø¬Ù„ ÙÙŠ Ø§Ù„Ø­Ø³Ø§Ø¨.',
  'Username': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
  'Recovery email': 'Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ù„Ù„Ø§Ø³ØªØ¹Ø§Ø¯Ø©',
  'New password': 'ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©',
  'Confirm password': 'ØªØ£ÙƒÙŠØ¯ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
  'Password updated. You can sign in with the new password now.':
      'ØªÙ… ØªØ­Ø¯ÙŠØ« ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±. ÙŠÙ…ÙƒÙ†Ùƒ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¨ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø© Ø§Ù„Ø¢Ù†.',
  'Updating...': 'Ø¬Ø§Ø±Ù Ø§Ù„ØªØ­Ø¯ÙŠØ«...',
  'Update Password': 'ØªØ­Ø¯ÙŠØ« ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
  'Username and password are required.': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… ÙˆÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ù…Ø·Ù„ÙˆØ¨Ø§Ù†.',
  'Sign in to SkillBite': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
  'Please enter your information below in order to login to your account':
      'ÙŠØ±Ø¬Ù‰ Ø¥Ø¯Ø®Ø§Ù„ Ø¨ÙŠØ§Ù†Ø§ØªÙƒ Ø£Ø¯Ù†Ø§Ù‡ Ù„ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¥Ù„Ù‰ Ø­Ø³Ø§Ø¨Ùƒ',
  'Enter your username': 'Ø£Ø¯Ø®Ù„ Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
  'Password': 'ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
  'Enter your password': 'Ø£Ø¯Ø®Ù„ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
  'Search here...': 'Ø§Ø¨Ø­Ø« Ù‡Ù†Ø§...',
  'Forgot Password?': 'Ù‡Ù„ Ù†Ø³ÙŠØª ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±ØŸ',
  'Signing in...': 'Ø¬Ø§Ø±Ù ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„...',
  'Log In': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
  'Demo Access': 'Ø§Ù„ÙˆØµÙˆÙ„ Ø§Ù„ØªØ¬Ø±ÙŠØ¨ÙŠ',
  'Owner Demo': 'ØªØ¬Ø±Ø¨Ø© Ø§Ù„Ù…Ø§Ù„Ùƒ',
  'Employee Demo': 'ØªØ¬Ø±Ø¨Ø© Ø§Ù„Ù…ÙˆØ¸Ù',
  'Create Account': 'Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨',
  'Create your business owner account to start using SkillBite.':
      'Ø£Ù†Ø´Ø¦ Ø­Ø³Ø§Ø¨ Ù„Ø¨Ø¯Ø¡ Ø§Ø³ØªØ®Ø¯Ø§Ù… SkillBite',
  'Full Name': 'Ø§Ù„Ø§Ø³Ù… Ø§Ù„ÙƒØ§Ù…Ù„',
  'Enter your full name': 'Ø£Ø¯Ø®Ù„ Ø§Ø³Ù…Ùƒ Ø§Ù„ÙƒØ§Ù…Ù„',
  'Email': 'Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
  'Enter your email': 'Ø£Ø¯Ø®Ù„ Ø¨Ø±ÙŠØ¯Ùƒ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
  'Company Name': 'Ø§Ø³Ù… Ø§Ù„Ø´Ø±ÙƒØ©',
  'Enter your company name': 'Ø£Ø¯Ø®Ù„ Ø§Ø³Ù… Ø§Ù„Ø´Ø±ÙƒØ©',
  'Phone Number': 'Ø±Ù‚Ù… Ø§Ù„Ø¬ÙˆØ§Ù„',
  'Enter your phone number': 'Ø£Ø¯Ø®Ù„ Ø±Ù‚Ù… Ø§Ù„Ø¬ÙˆØ§Ù„',
  'ID Number': 'Ø±Ù‚Ù… Ø§Ù„Ù‡ÙˆÙŠØ©',
  'Enter your ID number': 'Ø£Ø¯Ø®Ù„ Ø±Ù‚Ù… Ø§Ù„Ù‡ÙˆÙŠØ©',
  'Region': 'Ø§Ù„Ù…Ù†Ø·Ù‚Ø©',
  'SEC Business Line': 'Ù‚Ø·Ø§Ø¹ Ø£Ø¹Ù…Ø§Ù„ SEC',
  'Create account': 'Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨',
  'Creating account...': 'Ø¬Ø§Ø±Ù Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ø­Ø³Ø§Ø¨...',
  'Already have an account?': 'Ù„Ø¯ÙŠÙƒ Ø­Ø³Ø§Ø¨ Ø¨Ø§Ù„ÙØ¹Ù„ØŸ',
  'Eastern region': 'Ø§Ù„Ù…Ù†Ø·Ù‚Ø© Ø§Ù„Ø´Ø±Ù‚ÙŠØ©',
  'Central region': 'Ø§Ù„Ù…Ù†Ø·Ù‚Ø© Ø§Ù„ÙˆØ³Ø·Ù‰',
  'Western region': 'Ø§Ù„Ù…Ù†Ø·Ù‚Ø© Ø§Ù„ØºØ±Ø¨ÙŠØ©',
  'Northern region': 'Ø§Ù„Ù…Ù†Ø·Ù‚Ø© Ø§Ù„Ø´Ù…Ø§Ù„ÙŠØ©',
  'Southern region': 'Ø§Ù„Ù…Ù†Ø·Ù‚Ø© Ø§Ù„Ø¬Ù†ÙˆØ¨ÙŠØ©',
  'Distribution Contractors': 'Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø§Ù„ØªÙˆØ²ÙŠØ¹',
  'National Grid Contractors': 'Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø§Ù„Ø´Ø¨ÙƒØ© Ø§Ù„ÙˆØ·Ù†ÙŠØ©',
  'Projects Contractors': 'Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø§Ù„Ù…Ø´Ø§Ø±ÙŠØ¹',
  'Generation Contractors': 'Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø§Ù„ØªÙˆÙ„ÙŠØ¯',
  'Dawiyat Contractors': 'Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø¶ÙˆØ¦ÙŠØ§Øª',
  'HSSE Contractors': 'Ù…Ù‚Ø§ÙˆÙ„Ùˆ Ø§Ù„ØµØ­Ø© ÙˆØ§Ù„Ø³Ù„Ø§Ù…Ø© ÙˆØ§Ù„Ø¨ÙŠØ¦Ø©',
  'Material Sector': 'Ù‚Ø·Ø§Ø¹ Ø§Ù„Ù…ÙˆØ§Ø¯',
  'Facilities Sector': 'Ù‚Ø·Ø§Ø¹ Ø§Ù„Ù…Ø±Ø§ÙÙ‚',
  'Language': 'Ø§Ù„Ù„ØºØ©',
  'Arabic': 'Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©',
  'English': 'Ø§Ù„Ø¥Ù†Ø¬Ù„ÙŠØ²ÙŠØ©',
  'Home': 'Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©',
  'Employees': 'Ø§Ù„Ù…ÙˆØ¸ÙÙˆÙ†',
  'Titles': 'Ø§Ù„Ù…Ø³Ù…ÙŠØ§Øª',
  'Courses': 'Ø§Ù„Ø¯ÙˆØ±Ø§Øª',
  'Reports': 'Ø§Ù„ØªÙ‚Ø§Ø±ÙŠØ±',
  'Checklists': 'Ù‚ÙˆØ§Ø¦Ù… Ø§Ù„ØªØ­Ù‚Ù‚',
  'Chat': 'Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø©',
  'History': 'Ø§Ù„Ø³Ø¬Ù„',
  'Business Chat': 'Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„Ù†Ø´Ø§Ø·',
  'Team Chat': 'Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„ÙØ±ÙŠÙ‚',
  'Notifications': 'Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª',
  'Activity for ': 'Ø§Ù„Ù†Ø´Ø§Ø· Ù„Ù€ ',
  'Unread chat': 'Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø§Øª ØºÙŠØ± Ø§Ù„Ù…Ù‚Ø±ÙˆØ¡Ø©',
  'Pending courses': 'Ø§Ù„Ø¯ÙˆØ±Ø§Øª Ø§Ù„Ù…Ø¹Ù„Ù‚Ø©',
  'Pending checklists': 'Ù‚ÙˆØ§Ø¦Ù… Ø§Ù„ØªØ­Ù‚Ù‚ Ø§Ù„Ù…Ø¹Ù„Ù‚Ø©',
  'Active employees': 'Ø§Ù„Ù…ÙˆØ¸ÙÙˆÙ† Ø§Ù„Ù†Ø´Ø·ÙˆÙ†',
  'Active courses': 'Ø§Ù„Ø¯ÙˆØ±Ø§Øª Ø§Ù„Ù†Ø´Ø·Ø©',
  'All caught up': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ù†Ø§ØµØ± Ø¬Ø¯ÙŠØ¯Ø©',
  'There are no new notifications right now.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¥Ø´Ø¹Ø§Ø±Ø§Øª Ø¬Ø¯ÙŠØ¯Ø© Ø­Ø§Ù„ÙŠØ§Ù‹.',
  'new': 'Ø¬Ø¯ÙŠØ¯',
  'Recommendations': 'Ø§Ù„ØªÙˆØµÙŠØ§Øª',
  'No active courses.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¯ÙˆØ±Ø§Øª Ù†Ø´Ø·Ø©.',
  'Trending courses': 'Ø§Ù„Ø¯ÙˆØ±Ø§Øª Ø§Ù„Ø±Ø§Ø¦Ø¬Ø©',
  'View all': 'Ø¹Ø±Ø¶ Ø§Ù„ÙƒÙ„',
  'Best of the week': 'Ø§Ù„Ø£ÙØ¶Ù„ Ù‡Ø°Ø§ Ø§Ù„Ø£Ø³Ø¨ÙˆØ¹',
  'Today checklist': 'Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„ÙŠÙˆÙ…',
  'tasks': 'Ù…Ù‡Ø§Ù…',
  'No checklists assigned.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ù‚ÙˆØ§Ø¦Ù… ØªØ­Ù‚Ù‚ Ù…Ø®ØµØµØ©.',
  'Completed today': 'ØªÙ… Ø§Ù„Ø¥Ù†Ø¬Ø§Ø² Ø§Ù„ÙŠÙˆÙ…',
  'Pending checklist': 'Ù‚Ø§Ø¦Ù…Ø© ØªØ­Ù‚Ù‚ Ù…Ø¹Ù„Ù‚Ø©',
  'No courses assigned.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¯ÙˆØ±Ø§Øª Ù…Ø®ØµØµØ©.',
  'min': 'Ø¯Ù‚ÙŠÙ‚Ø©',
  'Open': 'ÙØªØ­',
  'Learning History': 'Ø³Ø¬Ù„ Ø§Ù„ØªØ¹Ù„Ù…',
  'No completed courses yet.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¯ÙˆØ±Ø§Øª Ù…ÙƒØªÙ…Ù„Ø© Ø¨Ø¹Ø¯.',
  'Details': 'Ø§Ù„ØªÙØ§ØµÙŠÙ„',
  'About the lesson': 'Ø¹Ù† Ø§Ù„Ø¯Ø±Ø³',
  'Lesson': 'Ø§Ù„Ø¯Ø±Ø³',
  'No mobile content items.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ù†Ø§ØµØ± Ù…Ø­ØªÙˆÙ‰ Ù„Ù„Ø¬ÙˆØ§Ù„.',
  'More content': 'Ù…Ø­ØªÙˆÙ‰ Ø¥Ø¶Ø§ÙÙŠ',
  'Continue': 'Ù…ØªØ§Ø¨Ø¹Ø©',
  'In progress': 'Ù‚ÙŠØ¯ Ø§Ù„ØªÙ‚Ø¯Ù…',
  'Completing...': 'Ø¬Ø§Ø±Ù Ø§Ù„Ø¥ÙƒÙ…Ø§Ù„...',
  'Exam': 'Ø§Ù„Ø§Ø®ØªØ¨Ø§Ø±',
  'Course Exam': 'Ø§Ø®ØªØ¨Ø§Ø± Ø§Ù„Ø¯ÙˆØ±Ø©',
  'Pass score ': 'Ø¯Ø±Ø¬Ø© Ø§Ù„Ù†Ø¬Ø§Ø­ ',
  'Question ': 'Ø§Ù„Ø³Ø¤Ø§Ù„ ',
  'Your answer': 'Ø¥Ø¬Ø§Ø¨ØªÙƒ',
  'Submitting...': 'Ø¬Ø§Ø±Ù Ø§Ù„Ø¥Ø±Ø³Ø§Ù„...',
  'Submit Exam': 'Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø§Ø®ØªØ¨Ø§Ø±',
  'Checklist': 'Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„ØªØ­Ù‚Ù‚',
  'Items': 'Ø§Ù„Ø¹Ù†Ø§ØµØ±',
  'No checklist items.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ù†Ø§ØµØ± ÙÙŠ Ø§Ù„Ù‚Ø§Ø¦Ù…Ø©.',
  'Already Completed': 'ØªÙ… Ø§Ù„Ø¥Ù†Ø¬Ø§Ø² Ù…Ø³Ø¨Ù‚Ø§Ù‹',
  'Complete Checklist': 'Ø¥ÙƒÙ…Ø§Ù„ Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„ØªØ­Ù‚Ù‚',
  'Workspace overview': 'Ù†Ø¸Ø±Ø© Ø¹Ø§Ù…Ø© Ø¹Ù„Ù‰ Ù…Ø³Ø§Ø­Ø© Ø§Ù„Ø¹Ù…Ù„',
  'Your people': 'ÙØ±ÙŠÙ‚Ùƒ',
  'No employees yet.': 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ù…ÙˆØ¸ÙÙˆÙ† Ø¨Ø¹Ø¯.',
  'Suggested course pushes': 'Ø§Ù„Ø¯ÙˆØ±Ø§Øª Ø§Ù„Ù…Ù‚ØªØ±Ø­Ø©',
  'No assignable courses.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¯ÙˆØ±Ø§Øª Ù‚Ø§Ø¨Ù„Ø© Ù„Ù„Ø¥Ø³Ù†Ø§Ø¯.',
  'Deactivate Employee': 'ØªØ¹Ø·ÙŠÙ„ Ø§Ù„Ù…ÙˆØ¸Ù',
  'Cancel': 'Ø¥Ù„ØºØ§Ø¡',
  'Deactivate': 'ØªØ¹Ø·ÙŠÙ„',
  'Create Employee': 'Ø¥Ù†Ø´Ø§Ø¡ Ù…ÙˆØ¸Ù',
  'Full name': 'Ø§Ù„Ø§Ø³Ù… Ø§Ù„ÙƒØ§Ù…Ù„',
  'Job title': 'Ø§Ù„Ù…Ø³Ù…Ù‰ Ø§Ù„ÙˆØ¸ÙŠÙÙŠ',
  'Saving...': 'Ø¬Ø§Ø±Ù Ø§Ù„Ø­ÙØ¸...',
  'Create': 'Ø¥Ù†Ø´Ø§Ø¡',
  'Add': 'Ø¥Ø¶Ø§ÙØ©',
  'Title name': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³Ù…Ù‰',
  'Job Titles': 'Ø§Ù„Ù…Ø³Ù…ÙŠØ§Øª Ø§Ù„ÙˆØ¸ÙŠÙÙŠØ©',
  'No job titles created.': 'Ù„Ù… ÙŠØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø³Ù…ÙŠØ§Øª ÙˆØ¸ÙŠÙÙŠØ© Ø¨Ø¹Ø¯.',
  'active employees': 'Ù…ÙˆØ¸ÙÙˆÙ† Ù†Ø´Ø·ÙˆÙ†',
  'Create Course': 'Ø¥Ù†Ø´Ø§Ø¡ Ø¯ÙˆØ±Ø©',
  'Title': 'Ø§Ù„Ø¹Ù†ÙˆØ§Ù†',
  'Description': 'Ø§Ù„ÙˆØµÙ',
  'Minutes': 'Ø§Ù„Ø¯Ù‚Ø§Ø¦Ù‚',
  'First content title': 'Ø¹Ù†ÙˆØ§Ù† Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø§Ù„Ø£ÙˆÙ„',
  'First content body': 'Ù†Øµ Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø§Ù„Ø£ÙˆÙ„',
  'Assign Course': 'Ø¥Ø³Ù†Ø§Ø¯ Ø¯ÙˆØ±Ø©',
  'assigned': 'Ù…ÙØ³Ù†Ø¯',
  'Has exam': 'ÙŠÙˆØ¬Ø¯ Ø§Ø®ØªØ¨Ø§Ø±',
  'No exam': 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø§Ø®ØªØ¨Ø§Ø±',
  'Manage Content': 'Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ù…Ø­ØªÙˆÙ‰',
  'Assign': 'Ø¥Ø³Ù†Ø§Ø¯',
  'Edit Content': 'ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ù…Ø­ØªÙˆÙ‰',
  'Add Content': 'Ø¥Ø¶Ø§ÙØ© Ù…Ø­ØªÙˆÙ‰',
  'Content type': 'Ù†ÙˆØ¹ Ø§Ù„Ù…Ø­ØªÙˆÙ‰',
  'Text': 'Ù†Øµ',
  'Link': 'Ø±Ø§Ø¨Ø·',
  'Body': 'Ø§Ù„Ù…Ø­ØªÙˆÙ‰',
  'Material URL': 'Ø±Ø§Ø¨Ø· Ø§Ù„Ù…Ø§Ø¯Ø©',
  'Order': 'Ø§Ù„ØªØ±ØªÙŠØ¨',
  'Update': 'ØªØ­Ø¯ÙŠØ«',
  'Delete Content': 'Ø­Ø°Ù Ø§Ù„Ù…Ø­ØªÙˆÙ‰',
  'Delete': 'Ø­Ø°Ù',
  'Course Content': 'Ù…Ø­ØªÙˆÙ‰ Ø§Ù„Ø¯ÙˆØ±Ø©',
  'Course': 'Ø§Ù„Ø¯ÙˆØ±Ø©',
  'No content items yet.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ù†Ø§ØµØ± Ù…Ø­ØªÙˆÙ‰ Ø¨Ø¹Ø¯.',
  'Edit': 'ØªØ¹Ø¯ÙŠÙ„',
  'Progress': 'Ø§Ù„ØªÙ‚Ø¯Ù…',
  'Overall completion rate: ': 'Ù…Ø¹Ø¯Ù„ Ø§Ù„Ø¥ÙƒÙ…Ø§Ù„ Ø§Ù„Ø¹Ø§Ù…: ',
  'Create Checklist': 'Ø¥Ù†Ø´Ø§Ø¡ Ù‚Ø§Ø¦Ù…Ø© ØªØ­Ù‚Ù‚',
  'Frequency': 'Ø§Ù„ØªÙƒØ±Ø§Ø±',
  'Daily': 'ÙŠÙˆÙ…ÙŠ',
  'Weekly': 'Ø£Ø³Ø¨ÙˆØ¹ÙŠ',
  'On demand': 'Ø¹Ù†Ø¯ Ø§Ù„Ø·Ù„Ø¨',
  'Assign to job title': 'Ø¥Ø³Ù†Ø§Ø¯ Ø¥Ù„Ù‰ Ù…Ø³Ù…Ù‰ ÙˆØ¸ÙŠÙÙŠ',
  'No automatic assignment': 'Ø¨Ø¯ÙˆÙ† Ø¥Ø³Ù†Ø§Ø¯ ØªÙ„Ù‚Ø§Ø¦ÙŠ',
  'Items, one per line': 'Ø§Ù„Ø¹Ù†Ø§ØµØ±ØŒ ÙƒÙ„ Ø¹Ù†ØµØ± ÙÙŠ Ø³Ø·Ø±',
  'Create Checklist Rule': 'Ø¥Ù†Ø´Ø§Ø¡ Ù‚Ø§Ø¹Ø¯Ø© Ø¥Ø³Ù†Ø§Ø¯',
  'Rule': 'Ù‚Ø§Ø¹Ø¯Ø©',
  'No checklists created.': 'Ù„Ù… ÙŠØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ù‚ÙˆØ§Ø¦Ù… ØªØ­Ù‚Ù‚ Ø¨Ø¹Ø¯.',
  'Assignment Rules': 'Ù‚ÙˆØ§Ø¹Ø¯ Ø§Ù„Ø¥Ø³Ù†Ø§Ø¯',
  'No checklist rules yet.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ù‚ÙˆØ§Ø¹Ø¯ Ø¥Ø³Ù†Ø§Ø¯ Ø¨Ø¹Ø¯.',
  'Send Team Message': 'Ø¥Ø±Ø³Ø§Ù„ Ø±Ø³Ø§Ù„Ø© Ù„Ù„ÙØ±ÙŠÙ‚',
  'Message': 'Ø§Ù„Ø±Ø³Ø§Ù„Ø©',
  'Sending...': 'Ø¬Ø§Ø±Ù Ø§Ù„Ø¥Ø±Ø³Ø§Ù„...',
  'Send': 'Ø¥Ø±Ø³Ø§Ù„',
  'Send Private Message': 'Ø¥Ø±Ø³Ø§Ù„ Ø±Ø³Ø§Ù„Ø© Ø®Ø§ØµØ©',
  'Need an account? Ask your business owner or administrator.':
      'ØªØ­ØªØ§Ø¬ Ø¥Ù„Ù‰ Ø­Ø³Ø§Ø¨ØŸ Ø§Ø·Ù„Ø¨Ù‡ Ù…Ù† Ù…Ø§Ù„Ùƒ Ø§Ù„Ù†Ø´Ø§Ø· Ø£Ùˆ Ø§Ù„Ù…Ø³Ø¤ÙˆÙ„.',
  'Recipient': 'Ø§Ù„Ù…Ø³ØªÙ„Ù…',
  'Write your message': 'Ø§ÙƒØªØ¨ Ø±Ø³Ø§Ù„ØªÙƒ',
  'Team': 'Ø§Ù„ÙØ±ÙŠÙ‚',
  'Private': 'Ø®Ø§Øµ',
  'Team Messages': 'Ø±Ø³Ø§Ø¦Ù„ Ø§Ù„ÙØ±ÙŠÙ‚',
  'No team messages yet.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø±Ø³Ø§Ø¦Ù„ ÙØ±ÙŠÙ‚ Ø¨Ø¹Ø¯.',
  'People': 'Ø§Ù„Ø£Ø´Ø®Ø§Øµ',
  'Person': 'Ø§Ù„Ø´Ø®Øµ',
  'No private messages yet.': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø±Ø³Ø§Ø¦Ù„ Ø®Ø§ØµØ© Ø¨Ø¹Ø¯.',
  'Could not load this file.': 'ØªØ¹Ø°Ø± ØªØ­Ù…ÙŠÙ„ Ù‡Ø°Ø§ Ø§Ù„Ù…Ù„Ù.',
  'Loading workspace...': 'Ø¬Ø§Ø±Ù ØªØ­Ù…ÙŠÙ„ Ù…Ø³Ø§Ø­Ø© Ø§Ù„Ø¹Ù…Ù„...',
  'Try again': 'Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰',
};
