import 'package:flutter/material.dart';

enum AppLanguage { en, ar }

class AppLanguageController {
  static ValueChanged<AppLanguage>? onChange;
}

bool isArabic(BuildContext context) =>
    Localizations.localeOf(context).languageCode == 'ar';

String tr(BuildContext context, String english) {
  if (!isArabic(context)) {
    return english;
  }
  return arabicStrings[english] ?? english;
}

const Map<String, String> arabicStrings = {
  'Reset Password': 'إعادة تعيين كلمة المرور',
  'Reset your password using your username and the recovery email saved on your account.':
      'أعد تعيين كلمة المرور باستخدام اسم المستخدم والبريد الإلكتروني المسجل في الحساب.',
  'Username': 'اسم المستخدم',
  'Recovery email': 'البريد الإلكتروني للاستعادة',
  'New password': 'كلمة المرور الجديدة',
  'Confirm password': 'تأكيد كلمة المرور',
  'Password updated. You can sign in with the new password now.':
      'تم تحديث كلمة المرور. يمكنك تسجيل الدخول بكلمة المرور الجديدة الآن.',
  'Updating...': 'جارٍ التحديث...',
  'Update Password': 'تحديث كلمة المرور',
  'Username and password are required.': 'اسم المستخدم وكلمة المرور مطلوبان.',
  'Sign in to SkillBite': 'تسجيل الدخول',
  'Please enter your information to login to your account':
      'يرجى إدخال بياناتك أدناه لتسجيل الدخول إلى حسابك',
  'Enter your username': 'أدخل اسم المستخدم',
  'Password': 'كلمة المرور',
  'Enter your password': 'أدخل كلمة المرور',
  'Search here...': 'ابحث هنا...',
  'Forgot Password?': 'هل نسيت كلمة المرور؟',
  'Signing in...': 'جارٍ تسجيل الدخول...',
  'Log In': 'تسجيل الدخول',
  'Demo Access': 'الوصول التجريبي',
  'Owner Demo': 'تجربة المالك',
  'Employee Demo': 'تجربة الموظف',
  'Need an account?': 'لا يوجد لديك حساب؟',
  'Create Account': 'إنشاء حساب',
  'Create an account to start using SkillBite':
      'أنشئ حساب لاستخدام التطبيق',
  'Full Name': 'الاسم الكامل',
  'Enter your full name': 'أدخل اسمك الكامل',
  'Email': 'البريد الإلكتروني',
  'Enter your email': 'أدخل بريدك الإلكتروني',
  'Company Name': 'اسم الشركة',
  'Enter your company name': 'أدخل اسم الشركة',
  'Phone Number': 'رقم الجوال',
  'Enter your phone number': 'أدخل رقم الجوال',
  'ID Number': 'رقم الهوية',
  'Enter your ID number': 'أدخل رقم الهوية',
  'Region': 'المنطقة',
  'SEC Business Line': 'قطاع أعمال SEC',
  'Create account': 'إنشاء حساب',
  'Creating account...': 'جارٍ إنشاء الحساب...',
  'Already have an account?': 'لديك حساب؟',
  'Eastern region': 'المنطقة الشرقية',
  'Central region': 'المنطقة الوسطى',
  'Western region': 'المنطقة الغربية',
  'Northern region': 'المنطقة الشمالية',
  'Southern region': 'المنطقة الجنوبية',
  'Distribution Contractors': 'مقاولو التوزيع',
  'National Grid Contractors': 'مقاولو الشبكة الوطنية',
  'Projects Contractors': 'مقاولو المشاريع',
  'Generation Contractors': 'مقاولو التوليد',
  'Dawiyat Contractors': 'مقاولو ضوئيات',
  'HSSE Contractors': 'مقاولو الصحة والسلامة والبيئة',
  'Material Sector': 'قطاع المواد',
  'Facilities Sector': 'قطاع المرافق',
  'Language': 'اللغة',
  'Arabic': 'العربية',
  'English': 'الإنجليزية',
  'Home': 'الرئيسية',
  'Employees': 'الموظفون',
  'Titles': 'المسميات',
  'Courses': 'الدورات',
  'Reports': 'التقارير',
  'Checklists': 'قوائم التحقق',
  'Chat': 'المحادثة',
  'History': 'السجل',
  'Business Chat': 'محادثة النشاط',
  'Team Chat': 'محادثة الفريق',
  'Notifications': 'الإشعارات',
  'Activity for ': 'النشاط لـ ',
  'Unread chat': 'المحادثات غير المقروءة',
  'Pending courses': 'الدورات المعلّقة',
  'Pending checklists': 'قوائم التحقق المعلّقة',
  'Active employees': 'الموظفون النشطون',
  'Active courses': 'الدورات النشطة',
  'All caught up': 'لا توجد عناصر جديدة',
  'There are no new notifications right now.': 'لا توجد إشعارات جديدة حالياً.',
  'new': 'جديد',
  'Recommendations': 'التوصيات',
  'No active courses.': 'لا توجد دورات نشطة.',
  'Trending courses': 'الدورات الرائجة',
  'View all': 'عرض الكل',
  'Best of the week': 'الأفضل هذا الأسبوع',
  'Today checklist': 'قائمة اليوم',
  'tasks': 'مهام',
  'No checklists assigned.': 'لا توجد قوائم تحقق مخصصة.',
  'Completed today': 'تم الإنجاز اليوم',
  'Pending checklist': 'قائمة تحقق معلّقة',
  'No courses assigned.': 'لا توجد دورات مخصصة.',
  'min': 'دقيقة',
  'Open': 'فتح',
  'Learning History': 'سجل التعلم',
  'No completed courses yet.': 'لا توجد دورات مكتملة بعد.',
  'Details': 'التفاصيل',
  'About the lesson': 'عن الدرس',
  'Lesson': 'الدرس',
  'No mobile content items.': 'لا توجد عناصر محتوى للجوال.',
  'More content': 'محتوى إضافي',
  'More courses': 'دورات إضافية',
  'Continue': 'متابعة',
  'Start Exam': '\u0628\u062f\u0621 \u0627\u0644\u0627\u062e\u062a\u0628\u0627\u0631',
  'In progress': 'قيد التقدم',
  'Completing...': 'جارٍ الإكمال...',
  'Exam': 'الاختبار',
  'Course Exam': 'اختبار الدورة',
  'Pass score': '\u062f\u0631\u062c\u0629 \u0627\u0644\u0646\u062c\u0627\u062d',
  'Pass score ': 'درجة النجاح ',
  'Question': '\u0627\u0644\u0633\u0624\u0627\u0644',
  'Question ': 'السؤال ',
  'Your answer': 'إجابتك',
  'Submitting...': 'جارٍ الإرسال...',
  'Submit Exam': 'إرسال الاختبار',
  'Checklist': 'قائمة التحقق',
  'Items': 'العناصر',
  'Notes': 'الملاحظات',
  'No checklist items.': 'لا توجد عناصر في القائمة.',
  'No notes were added.': 'لم تُضف أي ملاحظات.',
  'Add optional handoff or completion notes.':
      'أضف ملاحظات اختيارية للتسليم أو إتمام المهمة.',
  'Already Completed': 'تم الإنجاز مسبقاً',
  'Complete Checklist': 'إكمال قائمة التحقق',
  'Workspace overview': 'نظرة عامة على مساحة العمل',
  'Your people': 'فريقك',
  'No employees yet.': 'لا يوجد موظفون بعد.',
  'Assigned': 'المسند',
  'Completed': 'المكتمل',
  'Pending': 'المعلّق',
  'Pending today': 'لم يُكمل اليوم',
  'No checklist assigned': 'لا توجد قائمة تحقق مسندة',
  'Suggested course pushes': 'الدورات المقترحة',
  'No assignable courses.': 'لا توجد دورات قابلة للإسناد.',
  'Deactivate Employee': 'تعطيل الموظف',
  'Cancel': 'إلغاء',
  'Deactivate': 'تعطيل',
  'Create Employee': 'إنشاء موظف',
  'Full name': 'الاسم الكامل',
  'Job title': 'المسمى الوظيفي',
  'Saving...': 'جارٍ الحفظ...',
  'Create': 'إنشاء',
  'Add': 'إضافة',
  'Title name': 'اسم المسمى',
  'Job Titles': 'المسميات الوظيفية',
  'No job titles created.': 'لم يتم إنشاء مسميات وظيفية بعد.',
  'active employees': 'موظفون نشطون',
  'Create Course': 'إنشاء دورة',
  'Title': 'العنوان',
  'Description': 'الوصف',
  'Minutes': 'الدقائق',
  'First content title': 'عنوان المحتوى الأول',
  'First content body': 'نص المحتوى الأول',
  'Assign Course': 'إسناد دورة',
  'assigned': 'مُسند',
  'Has exam': 'يوجد اختبار',
  'No exam': 'لا يوجد اختبار',
  'Manage Content': 'إدارة المحتوى',
  'Assign': 'إسناد',
  'Edit Content': 'تعديل المحتوى',
  'Add Content': 'إضافة محتوى',
  'Content type': 'نوع المحتوى',
  'Text': 'نص',
  'Link': 'رابط',
  'Body': 'المحتوى',
  'Material URL': 'رابط المادة',
  'Order': 'الترتيب',
  'Update': 'تحديث',
  'Delete Content': 'حذف المحتوى',
  'Delete': 'حذف',
  'Course Content': 'محتوى الدورة',
  'Course': 'الدورة',
  'No content items yet.': 'لا توجد عناصر محتوى بعد.',
  'Edit': 'تعديل',
  'Progress': 'التقدم',
  'Overall completion rate: ': 'معدل الإكمال العام: ',
  'Create Checklist': 'إنشاء قائمة تحقق',
  'Frequency': 'التكرار',
  'Daily': 'يومي',
  'Weekly': 'أسبوعي',
  'On demand': 'عند الطلب',
  'Assign to job title': 'إسناد إلى مسمى وظيفي',
  'No automatic assignment': 'بدون إسناد تلقائي',
  'Items, one per line': 'العناصر، كل عنصر في سطر',
  'Create Checklist Rule': 'إنشاء قاعدة إسناد',
  'Rule': 'قاعدة',
  'No checklists created.': 'لم يتم إنشاء قوائم تحقق بعد.',
  'Assignment Rules': 'قواعد الإسناد',
  'No checklist rules yet.': 'لا توجد قواعد إسناد بعد.',
  'Send Team Message': 'إرسال رسالة للفريق',
  'Message': 'الرسالة',
  'Sending...': 'جارٍ الإرسال...',
  'Send': 'إرسال',
  'Send Private Message': 'إرسال رسالة خاصة',
  'Need an account? Ask your business owner or administrator.':
      'تحتاج إلى حساب؟ اطلبه من مالك النشاط أو المسؤول.',
  'Recipient': 'المستلم',
  'Write your message': 'اكتب رسالتك',
  'Team': 'الفريق',
  'Private': 'خاص',
  'Team Messages': 'رسائل الفريق',
  'No team messages yet.': 'لا توجد رسائل فريق بعد.',
  'People': 'الأشخاص',
  'Person': 'الشخص',
  'No private messages yet.': 'لا توجد رسائل خاصة بعد.',
  'Could not load this file.': 'تعذر تحميل هذا الملف.',
  'Could not load this video.':
      '\u062a\u0639\u0630\u0631 \u062a\u062d\u0645\u064a\u0644 \u0647\u0630\u0627 \u0627\u0644\u0641\u064a\u062f\u064a\u0648.',
  'Review the lesson content, then continue to the exam when you are ready.':
      'راجع محتوى الدرس ثم انتقل إلى الاختبار عندما تكون جاهزاً.',
  'Video lesson': 'درس فيديو',
  'PDF material': 'ملف PDF',
  'Loading workspace...': 'جارٍ تحميل مساحة العمل...',
  'Try again': 'حاول مرة أخرى',
};
