# Generated by Django 6.0.1 on 2026-01-20 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
        ('training', '0002_alter_enrollmentrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'شهادة / بطاقة اجتياز', 'verbose_name_plural': 'الشهادات وبطاقات الاجتياز'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('CERTIFICATE', 'شهادة'), ('PASS_CARD', 'بطاقة اجتياز')], max_length=20, verbose_name='نوع الاعتماد'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.enrollmentrequest', verbose_name='طلب التسجيل'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='ملف الشهادة'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.program', verbose_name='البرنامج التدريبي'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='رمز التحقق'),
        ),
    ]
