# Generated by Django 6.0.1 on 2026-01-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_alter_certificate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='اسم الدورة')),
                ('scorm_filename', models.CharField(max_length=255, verbose_name='ملف SCORM')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='ملف الشهادة')),
                ('verification_code', models.CharField(max_length=100, unique=True, verbose_name='رمز التحقق')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_certificates', to=settings.AUTH_USER_MODEL, verbose_name='المستفيد')),
            ],
            options={
                'verbose_name': 'شهادة SCORM',
                'verbose_name_plural': 'شهادات SCORM',
            },
        ),
        migrations.AddConstraint(
            model_name='scormcertificate',
            constraint=models.UniqueConstraint(fields=('owner', 'scorm_filename'), name='unique_scorm_certificate_per_user_file'),
        ),
    ]
