# Generated by Django 6.0.1 on 2026-03-16 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_certificate_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='program',
        ),
        migrations.AlterModelOptions(
            name='scormcertificate',
            options={'verbose_name': 'SCORM certificate', 'verbose_name_plural': 'SCORM certificates'},
        ),
        migrations.AlterField(
            model_name='scormcertificate',
            name='course_name',
            field=models.CharField(max_length=255, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='scormcertificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='scormcertificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Issued at'),
        ),
        migrations.AlterField(
            model_name='scormcertificate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiary'),
        ),
        migrations.AlterField(
            model_name='scormcertificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate file'),
        ),
        migrations.AlterField(
            model_name='scormcertificate',
            name='scorm_filename',
            field=models.CharField(max_length=255, verbose_name='SCORM package'),
        ),
        migrations.AlterField(
            model_name='scormcertificate',
            name='verification_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Verification code'),
        ),
    ]
