# Generated by Django 6.0.1 on 2026-03-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_remove_certificate_enrollment_and_more'),
        ('training', '0025_remove_enrollmentrequest_contractor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
