# Generated by Django 6.0.1 on 2026-01-20 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorprofile',
            options={'verbose_name': 'ملف مقاول', 'verbose_name_plural': 'ملفات المقاولين'},
        ),
        migrations.AlterModelOptions(
            name='trainerprofile',
            options={'verbose_name': 'ملف مدرب', 'verbose_name_plural': 'ملفات المدربين'},
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
