# Generated by Django 6.0.1 on 2026-01-26 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_contractorprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان الملف')),
                ('pdf_file', models.FileField(upload_to='contractor_docs/', verbose_name='ملف PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_documents', to=settings.AUTH_USER_MODEL, verbose_name='المقاول')),
            ],
            options={
                'verbose_name': 'ملف مقاول',
                'verbose_name_plural': 'ملفات المقاول',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
