# Generated by Django 6.0.1 on 2026-03-07 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contractorprofile_sec_business_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Business name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('industry', models.CharField(default='Food & Beverage', max_length=100, verbose_name='Industry')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_business', to=settings.AUTH_USER_MODEL, verbose_name='Business owner')),
            ],
            options={
                'verbose_name': 'Business tenant',
                'verbose_name_plural': 'Business tenants',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Job title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='accounts.businesstenant', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Job title',
                'verbose_name_plural': 'Job titles',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.businesstenant', verbose_name='Business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Employee user')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.jobtitle', verbose_name='Job title')),
            ],
            options={
                'verbose_name': 'Employee profile',
                'verbose_name_plural': 'Employee profiles',
                'ordering': ['business__name', 'user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_job_title_per_business'),
        ),
    ]
