# Generated by Django 6.0.1 on 2026-03-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businesstenant_jobtitle_employeeprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractordocument',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contractorprofile',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='contractorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='user',
        ),
    ]
