# Generated by Django 6.0.1 on 2026-03-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_contractordocument_owner_and_more'),
        ('training', '0025_remove_enrollmentrequest_contractor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractorDocument',
        ),
        migrations.DeleteModel(
            name='ContractorProfile',
        ),
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
    ]
