# Generated by Django 6.0.2 on 2026-02-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='courses', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='learning_paths', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='learningpathcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course'),
        ),
        migrations.AddField(
            model_name='learningpathcourse',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='courses',
            field=models.ManyToManyField(related_name='paths', through='learning.LearningPathCourse', to='learning.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learning.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.course'),
        ),
        migrations.AddField(
            model_name='module',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learning.quiz'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='sop',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learning.sop'),
        ),
        migrations.AddField(
            model_name='sopversion',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='learning.sop'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='learning_ch_tenant__131fd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'title'), name='uq_checklist_tenant_title'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['template', 'order'], name='learning_ch_templat_d0e280_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='uq_checklist_item_order'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant', 'status'], name='learning_co_tenant__80aa1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('tenant', 'title'), name='uq_course_tenant_title'),
        ),
        migrations.AddIndex(
            model_name='learningpathcourse',
            index=models.Index(fields=['path', 'order'], name='learning_le_path_id_af8a95_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningpathcourse',
            constraint=models.UniqueConstraint(fields=('path', 'course'), name='uq_path_course'),
        ),
        migrations.AddConstraint(
            model_name='learningpathcourse',
            constraint=models.UniqueConstraint(fields=('path', 'order'), name='uq_path_course_order'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['tenant', 'status'], name='learning_le_tenant__7480ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(fields=('tenant', 'title'), name='uq_path_tenant_title'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='learning_mo_course__7897c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uq_module_course_order'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question', 'is_correct'], name='learning_ch_questio_93353d_idx'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('tenant', 'title'), name='uq_quiz_tenant_title'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='learning_qu_quiz_id_eeeb66_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uq_question_quiz_order'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('tenant', 'title'), name='uq_resource_tenant_title'),
        ),
        migrations.AddIndex(
            model_name='sop',
            index=models.Index(fields=['tenant', 'is_active'], name='learning_so_tenant__94b47f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sop',
            constraint=models.UniqueConstraint(fields=('tenant', 'title'), name='uq_sop_tenant_title'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='learning_le_module__83c7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tenant', 'kind'], name='learning_le_tenant__734732_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='uq_lesson_module_order'),
        ),
        migrations.AddIndex(
            model_name='sopversion',
            index=models.Index(fields=['sop', 'published_at'], name='learning_so_sop_id_dd53b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sopversion',
            constraint=models.UniqueConstraint(fields=('sop', 'version'), name='uq_sop_version'),
        ),
    ]
