# Generated by Django 6.0.1 on 2026-01-18 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('COURSE_ATTENDANCE', 'دورة حضورية'), ('EXAM_ONLY', 'اختبار فقط'), ('E_LEARNING', 'دورة إلكترونية')], max_length=30)),
                ('outcome_type', models.CharField(choices=[('PASS_CARD', 'بطاقة اجتياز'), ('CERTIFICATE', 'شهادة')], max_length=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_payment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW_REQUEST', 'طلب جديد'), ('REJECTED', 'مرفوض'), ('INVOICE_ISSUED', 'مصدر له فاتورة'), ('WAITING_EXAM_SCHEDULING', 'بانتظار تحديد الموعد'), ('EXAM_SCHEDULED', 'تم تحديد الموعد'), ('EXAM_CONFIRMED', 'تم تأكيد الموعد'), ('IN_EXAM', 'جاري الاختبار'), ('FAILED', 'راسب'), ('CERTIFIED', 'حاصل على الشهادة'), ('COMPLETED_WITH_PASS_CARD', 'حاصل على بطاقة اجتياز')], default='NEW_REQUEST', max_length=40)),
                ('rejection_reason', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='training.enrollmentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='exam_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.examtemplate'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.program'),
        ),
    ]
