# Generated by Django 6.0.1 on 2026-01-20 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentrequest',
            options={'verbose_name': 'طلب تسجيل', 'verbose_name_plural': 'طلبات التسجيل'},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'verbose_name': 'محاولة اختبار', 'verbose_name_plural': 'محاولات الاختبارات'},
        ),
        migrations.AlterModelOptions(
            name='examtemplate',
            options={'verbose_name': 'قالب اختبار', 'verbose_name_plural': 'قوالب الاختبارات'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'برنامج تدريبي', 'verbose_name_plural': 'البرامج التدريبية'},
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='المقاول'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد الاختبار'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='exam_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.examtemplate', verbose_name='قالب الاختبار'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.program', verbose_name='البرنامج التدريبي'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('NEW_REQUEST', 'طلب جديد'), ('REJECTED', 'مرفوض'), ('INVOICE_ISSUED', 'مصدر له فاتورة'), ('WAITING_EXAM_SCHEDULING', 'بانتظار تحديد الموعد'), ('EXAM_SCHEDULED', 'تم تحديد الموعد'), ('EXAM_CONFIRMED', 'تم تأكيد الموعد'), ('IN_EXAM', 'جاري الاختبار'), ('FAILED', 'راسب'), ('CERTIFIED', 'حاصل على الشهادة'), ('COMPLETED_WITH_PASS_CARD', 'حاصل على بطاقة اجتياز')], default='NEW_REQUEST', max_length=40, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='المدرب'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الاختبار'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='training.enrollmentrequest', verbose_name='طلب التسجيل'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='ناجح'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت بدء الاختبار'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='مدة الاختبار (بالدقائق)'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم قالب الاختبار'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='total_questions',
            field=models.PositiveIntegerField(verbose_name='عدد الأسئلة'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(verbose_name='وصف البرنامج'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='program',
            name='outcome_type',
            field=models.CharField(choices=[('PASS_CARD', 'بطاقة اجتياز'), ('CERTIFICATE', 'شهادة')], max_length=30, verbose_name='نوع المخرج'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('COURSE_ATTENDANCE', 'دورة حضورية'), ('EXAM_ONLY', 'اختبار فقط'), ('E_LEARNING', 'دورة إلكترونية')], max_length=30, verbose_name='نوع البرنامج'),
        ),
        migrations.AlterField(
            model_name='program',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='يتطلب موافقة'),
        ),
        migrations.AlterField(
            model_name='program',
            name='requires_payment',
            field=models.BooleanField(default=True, verbose_name='يتطلب سداد'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255, verbose_name='اسم البرنامج'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(fields=('contractor', 'program'), name='unique_contractor_program_enrollment'),
        ),
    ]
