# Generated by Django 6.0.1 on 2026-01-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_enrollmentrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.examtemplate', verbose_name='قالب الاختبار')),
            ],
            options={
                'verbose_name': 'سؤال اختبار',
                'verbose_name_plural': 'أسئلة الاختبارات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
