# Generated by Django 6.0.1 on 2026-01-22 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_examquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب الخيار')),
                ('option_text', models.CharField(max_length=500, verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
            ],
            options={
                'verbose_name': 'خيار سؤال',
                'verbose_name_plural': 'خيارات الأسئلة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='شرح الإجابة (اختياري)'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='سؤال إلزامي'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='درجة السؤال'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ_SINGLE', 'اختيار من متعدد (إجابة واحدة)'), ('MCQ_MULTI', 'اختيار من متعدد (أكثر من إجابة)'), ('TRUE_FALSE', 'صح / خطأ'), ('SHORT_ANSWER', 'إجابة قصيرة'), ('ESSAY', 'مقالية')], default='MCQ_SINGLE', max_length=20, verbose_name='نوع السؤال'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='shuffle_options',
            field=models.BooleanField(default=True, verbose_name='خلط الخيارات'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات الاختبار'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='passing_score_percent',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='نسبة النجاح %'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='show_result_after_submit',
            field=models.BooleanField(default=True, verbose_name='إظهار النتيجة بعد التسليم'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='shuffle_questions',
            field=models.BooleanField(default=True, verbose_name='خلط الأسئلة'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='exam_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='training.examtemplate', verbose_name='قالب الاختبار'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأسئلة'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_question_order_per_template'),
        ),
        migrations.AddField(
            model_name='examoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='training.examquestion', verbose_name='السؤال'),
        ),
        migrations.AddConstraint(
            model_name='examoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_option_order_per_question'),
        ),
    ]
