# Generated by Django 6.0.1 on 2026-01-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contractordocument'),
        ('training', '0004_examoption_examquestion_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to='accounts.contractordocument', verbose_name='مرفقات المقاول'),
        ),
    ]
