# Generated by Django 6.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_enrollmentrequest_supporting_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='exam_code_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='هاش كود دخول الاختبار'),
        ),
    ]
