# Generated by Django 6.0.1 on 2026-02-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_enrollmentrequest_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='overall_passing_grade_percent',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='نسبة النجاح العامة %'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم البرنامج (عربي)'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم البرنامج (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('NEW_REQUEST', 'طلب جديد'), ('REJECTED', 'مرفوض'), ('INVOICE_ISSUED', 'فاتورة مصدرة'), ('PAYMENT_VERIFICATION', 'التحقق مع عملية السداد'), ('WAITING_EXAM_SCHEDULING', 'إنشاء موعد اختبار'), ('EXAM_SCHEDULED', 'حجز موعد الاختبار'), ('EXAM_CONFIRMED', 'الحضور لأداء الاختبار'), ('IN_EXAM', 'جاري الاختبار'), ('FAILED', 'لم يجتز الاختبار'), ('WAITING_PRACTICAL_GRADE', 'بانتظار إدخال درجة العملي'), ('CERTIFIED', 'شهادة مصدرة'), ('COMPLETED_WITH_PASS_CARD', 'بطاقة اجتياز مصدرة')], default='NEW_REQUEST', max_length=40, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('COURSE_ATTENDANCE', 'دورة حضورية'), ('EXAM_ONLY', 'اختبار فقط'), ('E_LEARNING', 'دورة إلكترونية'), ('TECHNICAL_EXAM', 'اختبار فني (عملي)'), ('SOLAR_POWER_EXAM', 'اختبار الطاقة الشمسية (نظري + عملي)')], max_length=30, verbose_name='نوع البرنامج'),
        ),
        migrations.CreateModel(
            name='ExternalPartAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('THEORETICAL', 'نظري'), ('PRACTICAL', 'عملي'), ('PROJECT', 'مشروع')], max_length=20, verbose_name='نوع الجزء')),
                ('grade_percent', models.PositiveSmallIntegerField(verbose_name='الدرجة %')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='external_assessments/', verbose_name='ملف التقييم (PDF)')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الإدخال')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_assessments', to='training.enrollmentrequest', verbose_name='طلب التسجيل')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_external_assessments', to=settings.AUTH_USER_MODEL, verbose_name='تم الإدخال بواسطة')),
            ],
            options={
                'verbose_name': 'تقييم خارجي',
                'verbose_name_plural': 'التقييمات الخارجية',
                'ordering': ['-submitted_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'part_type'), name='unique_external_assessment_per_enrollment_part')],
            },
        ),
        migrations.CreateModel(
            name='ProgramExamPartConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('THEORETICAL', 'نظري'), ('PRACTICAL', 'عملي'), ('PROJECT', 'مشروع')], max_length=20, verbose_name='جزء الاختبار')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب الجزء')),
                ('passing_grade_percent', models.PositiveSmallIntegerField(default=60, verbose_name='نسبة النجاح لهذا الجزء %')),
                ('is_required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_parts', to='training.program', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'تهيئة جزء اختبار للبرنامج',
                'verbose_name_plural': 'تهيئة أجزاء الاختبارات للبرامج',
                'ordering': ['program_id', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('program', 'order'), name='unique_part_order_per_program')],
            },
        ),
    ]
