# Generated by Django 6.0.1 on 2026-02-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contractorprofile_training_coordinator_fields'),
        ('training', '0009_program_overall_passing_grade_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان الملف')),
                ('pdf_file', models.FileField(upload_to='enrollment_supporting_docs/', verbose_name='ملف PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_document_snapshots', to='training.enrollmentrequest', verbose_name='طلب التسجيل')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_snapshots', to='accounts.contractordocument', verbose_name='المرفق الأصلي')),
            ],
            options={
                'verbose_name': 'مرفق طلب التسجيل',
                'verbose_name_plural': 'مرفقات طلبات التسجيل',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
