# Generated by Django 6.0.1 on 2026-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_program_renewal_window_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('COURSE_ATTENDANCE', 'دورة حضورية'), ('EXAM_ONLY', 'اختبار فقط'), ('E_LEARNING', 'دورة إلكترونية'), ('TECHNICAL_EXAM', 'اختبار فني'), ('SOLAR_POWER_EXAM', 'الطاقة الشمسية')], max_length=30, verbose_name='نوع البرنامج'),
        ),
    ]
