# Generated by Django 6.0.1 on 2026-03-07 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businesstenant_jobtitle_employeeprofile_and_more'),
        ('training', '0019_examsession_exam_code_plain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Course title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('estimated_minutes', models.PositiveIntegerField(default=15, verbose_name='Estimated duration (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.businesstenant', verbose_name='Business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lms_courses', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SOPChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Checklist title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('ON_DEMAND', 'On demand')], default='DAILY', max_length=20, verbose_name='Frequency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_checklists', to='accounts.businesstenant', verbose_name='Business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sop_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'SOP checklist',
                'verbose_name_plural': 'SOP checklists',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SOPChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_for', models.DateField(default=django.utils.timezone.localdate, verbose_name='Completion date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_completions', to='accounts.businesstenant', verbose_name='Business')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='training.sopchecklist', verbose_name='Checklist')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_completions', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'SOP checklist completion',
                'verbose_name_plural': 'SOP checklist completions',
                'ordering': ['-completed_for', '-completed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SOPChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Checklist item')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.sopchecklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'SOP checklist item',
                'verbose_name_plural': 'SOP checklist items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SOPChecklistItemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='Checked at')),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_completions', to='training.sopchecklistcompletion', verbose_name='Completion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='training.sopchecklistitem', verbose_name='Checklist item')),
            ],
            options={
                'verbose_name': 'SOP checklist item completion',
                'verbose_name_plural': 'SOP checklist item completions',
                'ordering': ['item__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20, verbose_name='Status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL, verbose_name='Assigned by')),
                ('assigned_via_job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to='accounts.jobtitle', verbose_name='Assigned via job title')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='accounts.businesstenant', verbose_name='Business')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.course', verbose_name='Course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Course assignment',
                'verbose_name_plural': 'Course assignments',
                'ordering': ['-assigned_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'employee'), name='unique_course_assignment_per_employee')],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_assignment_rules', to=settings.AUTH_USER_MODEL, verbose_name='Assigned by')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignment_rules', to='accounts.businesstenant', verbose_name='Business')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='training.course', verbose_name='Course')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignment_rules', to='accounts.jobtitle', verbose_name='Job title')),
            ],
            options={
                'verbose_name': 'Course assignment rule',
                'verbose_name_plural': 'Course assignment rules',
                'ordering': ['job_title__name', 'course__title', 'id'],
                'constraints': [models.UniqueConstraint(fields=('job_title', 'course'), name='unique_course_rule_per_job_title')],
            },
        ),
        migrations.CreateModel(
            name='SOPChecklistAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sop_assignment_rules', to=settings.AUTH_USER_MODEL, verbose_name='Assigned by')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_assignment_rules', to='accounts.businesstenant', verbose_name='Business')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='training.sopchecklist', verbose_name='Checklist')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_assignment_rules', to='accounts.jobtitle', verbose_name='Job title')),
            ],
            options={
                'verbose_name': 'SOP checklist assignment rule',
                'verbose_name_plural': 'SOP checklist assignment rules',
                'ordering': ['job_title__name', 'checklist__title', 'id'],
                'constraints': [models.UniqueConstraint(fields=('job_title', 'checklist'), name='unique_sop_rule_per_job_title')],
            },
        ),
        migrations.AddConstraint(
            model_name='sopchecklistcompletion',
            constraint=models.UniqueConstraint(fields=('checklist', 'employee', 'completed_for'), name='unique_daily_sop_completion'),
        ),
        migrations.AddConstraint(
            model_name='sopchecklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'order'), name='unique_sop_item_order_per_checklist'),
        ),
        migrations.AddConstraint(
            model_name='sopchecklistitemcompletion',
            constraint=models.UniqueConstraint(fields=('completion', 'item'), name='unique_item_completion_per_checklist_run'),
        ),
    ]
