# Generated by Django 6.0.1 on 2026-03-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_course_sopchecklist_sopchecklistcompletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('LESSON', 'Lesson'), ('TEXT', 'Text'), ('MATERIAL', 'Material')], default='LESSON', max_length=20, verbose_name='Content type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(blank=True, default='', verbose_name='Body')),
                ('material_url', models.URLField(blank=True, default='', verbose_name='Material URL')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='training.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course content item',
                'verbose_name_plural': 'Course content items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
