# Generated by Django 6.0.1 on 2026-03-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_coursecontentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontentitem',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to='course_content_pdfs/', verbose_name='PDF file'),
        ),
    ]
