# Generated by Django 6.0.1 on 2026-03-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_coursecontentitem_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontentitem',
            name='video_file',
            field=models.FileField(blank=True, default='', upload_to='course_content_videos/', verbose_name='Video file'),
        ),
    ]
