# Generated by Django 6.0.1 on 2026-03-16 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_remove_certificate_enrollment_and_more'),
        ('training', '0024_courseexamsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='exam_session',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='exam_template',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='program',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='source_certificate',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='supporting_documents',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='enrollmentsupportingdocument',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='enrollmentsupportingdocument',
            name='source_document',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='exam_template',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='program',
        ),
        migrations.RemoveConstraint(
            model_name='externalpartassessment',
            name='unique_external_assessment_per_enrollment_part',
        ),
        migrations.RemoveConstraint(
            model_name='programexampartconfig',
            name='unique_part_order_per_program',
        ),
        migrations.AlterModelOptions(
            name='examoption',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Exam option', 'verbose_name_plural': 'Exam options'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Exam question', 'verbose_name_plural': 'Exam questions'},
        ),
        migrations.AlterModelOptions(
            name='examtemplate',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Exam template', 'verbose_name_plural': 'Exam templates'},
        ),
        migrations.AlterField(
            model_name='examoption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='examoption',
            name='option_text',
            field=models.CharField(max_length=500, verbose_name='Option text'),
        ),
        migrations.AlterField(
            model_name='examoption',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='examoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='training.examquestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_text',
            field=models.TextField(verbose_name='Question text'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ_SINGLE', 'Single choice'), ('MCQ_MULTI', 'Multiple choice'), ('TRUE_FALSE', 'True / False'), ('SHORT_ANSWER', 'Short answer'), ('ESSAY', 'Essay')], default='MCQ_SINGLE', max_length=20, verbose_name='Question type'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='shuffle_options',
            field=models.BooleanField(default=True, verbose_name='Shuffle options'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.examtemplate', verbose_name='Exam template'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Exam duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='instructions',
            field=models.TextField(blank=True, default='', verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Exam template name'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='passing_score_percent',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Passing score %'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='show_result_after_submit',
            field=models.BooleanField(default=True, verbose_name='Show result after submit'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='shuffle_questions',
            field=models.BooleanField(default=True, verbose_name='Shuffle questions'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Total questions'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
        migrations.DeleteModel(
            name='EnrollmentSupportingDocument',
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
        migrations.RemoveField(
            model_name='externalpartassessment',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='externalpartassessment',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='programexampartconfig',
            name='program',
        ),
        migrations.DeleteModel(
            name='EnrollmentRequest',
        ),
        migrations.DeleteModel(
            name='ExternalPartAssessment',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramExamPartConfig',
        ),
    ]
