# Generated by Django 6.0.1 on 2026-03-17 11:53

from django.db import migrations


def remove_legacy_job_title_course_assignments(apps, schema_editor):
    CourseAssignment = apps.get_model('training', 'CourseAssignment')
    CourseAssignment.objects.exclude(assigned_via_job_title__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_remove_enrollmentrequest_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseassignmentrule',
            name='unique_course_rule_per_job_title',
        ),
        migrations.RunPython(
            remove_legacy_job_title_course_assignments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='assigned_via_job_title',
        ),
        migrations.DeleteModel(
            name='CourseAssignmentRule',
        ),
    ]
