# Generated by Django 6.0.1 on 2026-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_coursebusinessassignment_and_global_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'مدرجة'), ('IN_PROGRESS', 'جاري التنفيذ'), ('COMPLETED', 'مكتمل')], default='ASSIGNED', max_length=20, verbose_name='Status'),
        ),
    ]
